### ISSUE TITLE
responsive design mvp

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/perf-land#4]
@paulathevalley, you made perf land look like a Real Thing! Thank you! 

The mobile needs some work now, though. I don't think we need a big overhaul; we can just tweak the existing layout.

Let me know if you don't want to take this on—I can definitely do it.

![image](https://user-images.githubusercontent.com/2822048/82153174-24fc1900-9823-11ea-9ac9-d7cbe5b1e884.png)

![image](https://user-images.githubusercontent.com/2822048/82153235-7b695780-9823-11ea-8924-25d45a93df35.png)

**Comment by paulathevalley** [comment]
aye aye! I'm on it

**Comment by paulathevalley** [comment]
Not perfect yet, but it’s okie dokie for now
